---
- name: metal_get_ocp_metal_vlans
  uri:
    url: https://api.equinix.com/metal/v1/projects/{{metal_project_id}}/virtual-networks
    method: GET
    headers:
      X-Auth-Token: "{{ metal_api_token }}"
    status_code: [200]
  register: metal_get_ocp_metal_vlans_output

- name: metal_get_ocp_vlan_id
  ansible.builtin.set_fact:
    ocp_vlan_id: "{{ item.get('id')}}"
  loop: "{{ metal_get_ocp_metal_vlans_output.get('json')['virtual_networks'] }}"
  when: item.get('vxlan') == metal_ocp_vlan
