- name: metal_attach_ocp_networking_hosts_vlan
  uri:
    url: https://api.equinix.com/metal/v1/ports/{{ item | json_query(query_string) | first }}/convert/layer-2
    method: POST
    headers: 
      X-Auth-Token: "{{ metal_api_token }}"
    body_format: json
    body:
      vnid: "{{ metal_ocp_vlan }}" 
    status_code: [200, 422]
    timeout: 120
  # no_log: true
  loop: "{{ metal_hosts_provision_ocp_control_get_details.results |  map(attribute='content') | map('from_json') }}" 
  vars:
    query_string: 'network_ports[?name==''bond0''].id'
  loop_control:
    pause: 5
