---

- name: metal_get_ip_reservations
  uri:
    url: "https://api.equinix.com/metal/v1/projects/{{ metal_project_id }}/ips"
    method: GET
    headers:
      X-Auth-Token: "{{ metal_api_token }}"
    status_code: [200]
  register: metal_get_ip_reservations_output

- name: metal_get_ocp_ip_reservation_id
  ansible.builtin.set_fact:
    ocp_ip_reservation_id: "{{ item[0].get('id') }}"
  loop: "{{ metal_get_ip_reservations_output.json.get('ip_addresses') | subelements('tags') }}"
  when: 'metal_ocp_domain in item'
  ignore_errors: true
  no_log: true

- name: metal_provision_ocp_ip_reservation
  uri:
    url: "https://api.equinix.com/metal/v1/projects/{{ metal_project_id }}/ips"
    method: POST
    headers:
      X-Auth-Token: "{{ metal_api_token }}"
      Content-Type: "application/json"
      Accept: application/json
    body_format: json
    body:
      type: "public_ipv4"
      quantity: "{{ metal_ip_block_size }}"
      comments: "{{ metal_ocp_domain }}"
      metro: "{{ metal_metro }}"
      tags:
        - "{{ metal_ocp_domain }}"
        - "ocp"
      fail_on_approval_required: "True"
    return_content: true
    status_code: [201, 422]
  when: ocp_ip_reservation_id is undefined
  register: metal_provision_ocp_ip_reservation_output
  changed_when: metal_provision_ocp_ip_reservation_output.status == 201

- name: metal_provision_ocp_ip_reservation_wait
  ansible.builtin.pause:
    seconds: 5
  when: metal_provision_ocp_ip_reservation_output.changed

- name: metal_get_ip_reservations
  uri:
    url: "https://api.equinix.com/metal/v1/projects/{{ metal_project_id }}/ips"
    method: GET
    headers:
      X-Auth-Token: "{{ metal_api_token }}"
    status_code: [200]
  register: metal_get_ip_reservations_output

- name: metal_get_ocp_ip_reservation_id
  ansible.builtin.set_fact:
    ocp_ip_reservation_id: "{{ item[0].get('id') }}"
  loop: "{{ metal_get_ip_reservations_output.json.get('ip_addresses') | subelements('tags') }}"
  when: 'metal_ocp_domain in item'
  ignore_errors: true
  no_log: true

- name: metal_get_ocp_ip_details
  ansible.builtin.set_fact:
    ocp_ips_reservation_id: "{{ item[0].get('id') }}"
    ocp_ips_reservation_network: "{{ item[0].get('network') }}"
    ocp_ips_reservation_cidr: "{{ item[0].get('cidr') }}"
    ocp_ips_reservation_network_cidr: "{{ item[0].get('network') }}/{{ item[0].get('cidr') }}"
  loop: "{{ metal_get_ip_reservations_output.json.get('ip_addresses') | subelements('tags') }}"
  when: 'metal_ocp_domain in item'

- name: metal_set_ocp_ip_deployment_details
  ansible.builtin.set_fact:
    ocp_ips_gateway_ip: "{{ ocp_ips_reservation_network_cidr | ansible.utils.nthhost(1) }}"
    ocp_ips_opsbox_ip: "{{ ocp_ips_reservation_network_cidr | ansible.utils.nthhost(2) }}"
    ocp_ips_apps_ip: "{{ ocp_ips_reservation_network_cidr | ansible.utils.nthhost(3) }}"
    ocp_ips_api_ip: "{{ ocp_ips_reservation_network_cidr | ansible.utils.nthhost(4) }}"
    ocp_ips_first_dhcp_ip: "{{ ocp_ips_reservation_network_cidr | ansible.utils.nthhost(5) }}"
    ocp_ips_last_dhcp_ip: "{{ ocp_ips_reservation_network_cidr | ansible.utils.nthhost(-2) }}"
