---
- name: metal_provision_ocp_vlan
  uri:
    url: "https://api.equinix.com/metal/v1/projects/{{ metal_project_id }}/virtual-networks"
    method: POST
    headers:
      X-Auth-Token: "{{ metal_api_token }}"
    body_format: json
    body:
      metro: "{{ metal_metro }}"
      vxlan: "{{ metal_ocp_vlan }}"
      description: "{{ metal_ocp_domain }}"
    status_code: [201, 422]
