---
- include_role:
    name: metal
    tasks_from: metal_get_or_provision_ocp_ip_reservation.yaml
- include_role:
    name: metal
    tasks_from: metal_build_ip_host_table.yaml

- include_tasks: redhat_cloud_get_refresh_token.yaml
- include_tasks: redhat_cloud_get_openshift_clusters.yaml
- include_tasks: redhat_cloud_get_openshift_infra_envs.yaml

- include_tasks: redhat_cloud_build_ip_host_id_table.yaml
- include_tasks: redhat_cloud_openshift_cluster_rename_hosts.yaml