- name: redhat_cloud_delete_openshift_cluster
  uri:
    url: "https://{{ redhat_assisted_service_api }}/api/assisted-install/v2/clusters/{{ openshift_cluster_id }}"
    method: DELETE
    headers: 
      accept: application/json
      Authorization: "Bearer {{ redhat_cloud_openshift_access_token }}"
    status_code: 200, 204

- name: redhat_cloud_delete_openshift_infra_env
  uri:
    url: "https://{{ redhat_assisted_service_api }}/api/assisted-install/v2/infra-envs/{{ openshift_infra_env_id }}"
    method: DELETE
    headers: 
      accept: application/json
      Authorization: "Bearer {{ redhat_cloud_openshift_access_token }}"
    status_code: 200, 204