---
- name: redhat_cloud_openshift_get_refresh_token
  uri:
    url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    method: POST
    body_format: form-urlencoded
    body:
      grant_type: refresh_token
      client_id: cloud-services
      refresh_token: "{{ redhat_cloud_openshift_token }}"
    status_code: [200, 201, 422]
  register: redhat_cloud_openshift_refresh_token

- name: redhat_cloud_openshift_set_access_token
  ansible.builtin.set_fact:
    redhat_cloud_openshift_access_token: "{{ redhat_cloud_openshift_refresh_token.json.get('access_token') }}"
